import { useEffect, useState } from 'react';
import { Activity, AlertTriangle, BarChart3, CheckCircle2, ChevronRight, Database, FileUp, Gauge, History, RefreshCw, Server, ShieldCheck, SlidersHorizontal, Upload, XCircle, Zap } from 'lucide-react';

type Page = 'dashboard' | 'signal' | 'vmd' | 'diagnosis' | 'training' | 'history' | 'system';
type HealthStatus = { status: string; system: string; version: string; environment: string };
type SystemStatus = { status: string; active_model: string; model_version: string; model_accuracy: number; feature_count: number; components: Record<string, string> };
type HistoryItem = { id: number; timestamp: string; filename: string; machine_id: string; predicted_fault: string; confidence: number; severity: string; health_score: number; optimized_K: number; recommended_action: string };
type SignalAnalysis = { metadata: { sampling_rate: number; rpm: string | number; load_hp: string | number; machine_id: string }; sample_count: number; duration_sec: number; time_stats: Record<string, number>; frequency_stats: Record<string, number>; time_series_preview: number[]; fft_spectrum: { frequencies: number[]; magnitudes: number[] } };
type Prediction = { prediction_id: number | null; timestamp: string; predicted_fault: string; confidence: number; severity: string; health_score: number; class_probabilities: Record<string, number>; optimized_K: number; optimized_alpha: number; reconstruction_error: number; top_features: { feature_name: string; importance: number; shap_value: number; feature_value: number }[]; imf_attribution: Record<string, number>; recommended_action: string };

const navItems: { id: Page; label: string; icon: typeof Gauge }[] = [
  { id: 'dashboard', label: 'Overview', icon: Gauge }, { id: 'signal', label: 'Signal Lab', icon: Activity }, { id: 'vmd', label: 'VMD Explorer', icon: BarChart3 },
  { id: 'diagnosis', label: 'Diagnosis', icon: ShieldCheck }, { id: 'training', label: 'Model Training', icon: Database }, { id: 'history', label: 'History', icon: History }, { id: 'system', label: 'System', icon: SlidersHorizontal },
];

function Stat({ label, value, detail, tone = 'cyan' }: { label: string; value: string; detail?: string; tone?: 'cyan' | 'green' | 'amber' | 'red' }) {
  return <div className="panel stat"><div className={`stat-icon ${tone}`}><Zap size={17} /></div><div><p className="eyebrow">{label}</p><p className="stat-value">{value}</p>{detail && <p className="muted">{detail}</p>}</div></div>;
}

function Waveform({ values, color = '#43d9c5' }: { values: number[]; color?: string }) {
  if (!values.length) return <div className="chart-empty">Upload a signal to render telemetry.</div>;
  const min = Math.min(...values); const max = Math.max(...values); const span = max - min || 1;
  const points = values.map((value, i) => `${(i / Math.max(values.length - 1, 1)) * 100},${92 - ((value - min) / span) * 78}`).join(' ');
  return <svg className="waveform" viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Vibration waveform"><polyline points={points} fill="none" stroke={color} strokeWidth="1.4" vectorEffect="non-scaling-stroke" /></svg>;
}

export default function App() {
  const [page, setPage] = useState<Page>('dashboard'); const [health, setHealth] = useState<HealthStatus | null>(null); const [system, setSystem] = useState<SystemStatus | null>(null); const [history, setHistory] = useState<HistoryItem[]>([]); const [analysis, setAnalysis] = useState<SignalAnalysis | null>(null); const [prediction, setPrediction] = useState<Prediction | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [fileName, setFileName] = useState<string | null>(null); const [selectedFile, setSelectedFile] = useState<File | null>(null);

  const refresh = async () => { setLoading(true); setError(null); try { const [healthRes, systemRes, historyRes] = await Promise.all([fetch('/api/health'), fetch('/api/v1/system/status'), fetch('/api/v1/predict/history?limit=8')]); if (!healthRes.ok || !systemRes.ok || !historyRes.ok) throw new Error('Backend returned an unavailable response.'); setHealth(await healthRes.json()); setSystem(await systemRes.json()); setHistory(await historyRes.json()); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to reach the VibraGuard API.'); } finally { setLoading(false); } };
  useEffect(() => { refresh(); }, []);

  const handleFile = async (file: File) => { setBusy(true); setError(null); setFileName(file.name); setSelectedFile(file); try { const form = new FormData(); form.append('file', file); const response = await fetch('/api/v1/signal/upload', { method: 'POST', body: form }); if (!response.ok) throw new Error((await response.json()).detail || 'Signal analysis failed.'); setAnalysis(await response.json()); setPage('signal'); } catch (err) { setError(err instanceof Error ? err.message : 'Signal upload failed.'); } finally { setBusy(false); } };
  const diagnose = async () => { if (!selectedFile) { setError('Upload a CSV signal before requesting a diagnosis.'); return; } setBusy(true); setError(null); try { const form = new FormData(); form.append('file', selectedFile); const response = await fetch('/api/v1/predict/file', { method: 'POST', body: form }); if (!response.ok) throw new Error((await response.json()).detail || 'Diagnosis failed.'); setPrediction(await response.json()); setPage('diagnosis'); await refresh(); } catch (err) { setError(err instanceof Error ? err.message : 'Diagnosis failed.'); } finally { setBusy(false); } };

  const healthScore = prediction?.health_score; const currentStatus = prediction?.severity || 'Awaiting signal';
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><Activity size={22} /></div><div><strong>VIBRA<span>GUARD</span></strong><small>Condition intelligence</small></div></div><div className="rail-label">WORKSPACE</div><nav>{navItems.map(({ id, label, icon: Icon }) => <button key={id} className={page === id ? 'nav-item active' : 'nav-item'} onClick={() => setPage(id)}><Icon size={18} /><span>{label}</span>{page === id && <ChevronRight size={15} />}</button>)}</nav><div className="sidebar-foot"><div className="pulse-dot" /> <span>Sensor gateway ready</span><small>CSV / API input</small></div></aside><main className="main"><header className="topbar"><div><p className="eyebrow">MACHINE HEALTH / CONTROL ROOM</p><h1>{navItems.find(item => item.id === page)?.label}</h1></div><div className="top-actions"><span className={`status-chip ${health ? 'online' : 'offline'}`}><span /> API {health ? 'ONLINE' : loading ? 'CHECKING' : 'OFFLINE'}</span><button className="icon-button" onClick={refresh} disabled={loading} title="Refresh system status"><RefreshCw size={17} className={loading ? 'spin' : ''} /></button></div></header>{error && <div className="error-banner"><AlertTriangle size={17} />{error}<button onClick={() => setError(null)}><XCircle size={16} /></button></div>}<section className="content">{page === 'dashboard' && <Dashboard system={system} history={history} prediction={prediction} analysis={analysis} healthScore={healthScore} currentStatus={currentStatus} setPage={setPage} />}{page === 'signal' && <SignalLab analysis={analysis} busy={busy} fileName={fileName} onFile={handleFile} onDiagnose={diagnose} />}{page === 'vmd' && <UnavailablePage title="VMD Explorer" detail="The decomposition endpoint is ready; this view will render IMFs after a signal is selected." icon={BarChart3} />}{page === 'diagnosis' && <Diagnosis prediction={prediction} />}{page === 'training' && <UnavailablePage title="Model Training" detail="Training controls will appear here when the training-run API is connected." icon={Database} />}{page === 'history' && <HistoryPage history={history} />}{page === 'system' && <SystemPage system={system} health={health} />}</section></main></div>;
}

function Dashboard({ system, history, prediction, analysis, healthScore, currentStatus, setPage }: { system: SystemStatus | null; history: HistoryItem[]; prediction: Prediction | null; analysis: SignalAnalysis | null; healthScore?: number; currentStatus: string; setPage: (page: Page) => void }) { return <><div className="hero-row"><div><span className="kicker"><span className="pulse-dot" /> LIVE API / RESULTS ARE EXPLICIT</span><h2>See the machine before it stops.</h2><p className="hero-copy">A signal-first workspace for adaptive VMD, fault classification, and explainable maintenance decisions.</p></div><button className="primary-button" onClick={() => setPage('signal')}><Upload size={17} /> Inspect a signal</button></div><div className="stats-grid"><Stat label="Overall health" value={healthScore !== undefined ? `${healthScore.toFixed(0)} / 100` : 'N/A'} detail="Engineering heuristic" tone={healthScore !== undefined && healthScore < 60 ? 'red' : 'green'} /><Stat label="Current condition" value={currentStatus} detail={prediction ? `Confidence ${(prediction.confidence * 100).toFixed(1)}%` : 'No prediction yet'} tone={prediction ? 'amber' : 'cyan'} /><Stat label="Active model" value={system?.model_version || 'N/A'} detail={system?.active_model || 'Model not loaded'} /><Stat label="Signals analyzed" value={history.length ? `${history.length}` : '0'} detail="Stored predictions" /></div><div className="dashboard-grid"><div className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">VIBRATION TREND</p><h3>{analysis ? 'Latest analyzed window' : 'Awaiting telemetry'}</h3></div><BarChart3 size={19} className="heading-icon" /></div><Waveform values={analysis?.time_series_preview || []} /><div className="chart-footer"><span>Amplitude</span><span>{analysis ? 'Processed signal' : 'No data'}</span></div></div><div className="panel alert-panel"><div className="panel-heading"><div><p className="eyebrow">RECENT EVENTS</p><h3>Maintenance queue</h3></div><AlertTriangle size={19} className="heading-icon amber" /></div>{history.length ? history.slice(0, 4).map(item => <div className="event-row" key={item.id}><span className={`severity-dot ${item.severity.includes('HIGH') ? 'red' : 'amber'}`} /><div><strong>{item.predicted_fault}</strong><small>{item.machine_id} · {item.timestamp}</small></div><b>{item.health_score.toFixed(0)}</b></div>) : <div className="empty-state"><Database size={22} /><p>No stored alerts</p><small>Results from real runs will appear here.</small></div>}</div></div></>; }

function UnavailablePage({ title, detail, icon: Icon }: { title: string; detail: string; icon: typeof BarChart3 }) { return <div className="panel empty-large"><Icon size={25} /><h3>{title} is not connected yet</h3><p>{detail}</p><span className="status-chip offline">SERVER INTEGRATION PENDING</span></div>; }

function SignalLab({ analysis, busy, fileName, onFile, onDiagnose }: { analysis: SignalAnalysis | null; busy: boolean; fileName: string | null; onFile: (file: File) => void; onDiagnose: () => void }) { return <><div className="lab-header"><div><p className="eyebrow">SIGNAL ANALYSIS / CSV INGESTION</p><h2>Signal Lab</h2><p className="muted large">Upload a vibration window and inspect the server-side preprocessing result.</p></div>{analysis && <button className="primary-button" onClick={onDiagnose} disabled={busy}><ShieldCheck size={17} /> Run diagnosis</button>}</div><label className="upload-zone"><input type="file" accept=".csv,.txt" onChange={event => event.target.files?.[0] && onFile(event.target.files[0])} /><FileUp size={27} /><strong>{busy ? 'Processing signal...' : fileName || 'Drop a CSV vibration file here'}</strong><span>CSV or TXT · minimum 128 numeric samples · metadata remains explicit</span></label>{analysis ? <><div className="stats-grid compact"><Stat label="Samples" value={analysis.sample_count.toLocaleString()} detail={`${analysis.duration_sec.toFixed(3)} sec`} /><Stat label="Sampling rate" value={`${analysis.metadata.sampling_rate} Hz`} detail="Provided / default" /><Stat label="RMS" value={analysis.time_stats.rms.toFixed(4)} detail="Normalized window" tone="green" /><Stat label="Dominant frequency" value={`${analysis.frequency_stats.dominant_freq.toFixed(1)} Hz`} detail="FFT peak" tone="amber" /></div><div className="dashboard-grid"><div className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">TIME DOMAIN</p><h3>Processed waveform</h3></div><Activity size={19} className="heading-icon" /></div><Waveform values={analysis.time_series_preview} /><div className="chart-footer"><span>Amplitude</span><span>Detrend + z-score</span></div></div><div className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">FREQUENCY DOMAIN</p><h3>FFT spectrum</h3></div><BarChart3 size={19} className="heading-icon" /></div><Waveform values={analysis.fft_spectrum.magnitudes} color="#f6b94b" /><div className="chart-footer"><span>Magnitude</span><span>0 - Nyquist</span></div></div></div></> : <div className="panel empty-large"><Upload size={24} /><h3>Analysis canvas is clear</h3><p>Upload a real vibration CSV to populate waveform, FFT, and condition indicators.</p></div>}</>; }

function Diagnosis({ prediction }: { prediction: Prediction | null }) { return <>{prediction ? <><div className="diagnosis-hero"><div><p className="eyebrow">MODEL DIAGNOSIS / REAL RUN</p><h2>{prediction.predicted_fault}</h2><p className="muted large">{prediction.recommended_action}</p></div><div className="health-ring"><strong>{prediction.health_score.toFixed(0)}</strong><span>HEALTH</span></div></div><div className="dashboard-grid"><div className="panel"><div className="panel-heading"><h3>Probability distribution</h3><span className="status-chip online">{prediction.severity}</span></div>{Object.entries(prediction.class_probabilities).map(([label, value]) => <div className="prob-row" key={label}><div><span>{label}</span><b>{(value * 100).toFixed(1)}%</b></div><div className="progress"><i style={{ width: `${value * 100}%` }} /></div></div>)}</div><div className="panel"><div className="panel-heading"><h3>Top contributing features</h3><ShieldCheck size={19} className="heading-icon" /></div>{prediction.top_features.map(feature => <div className="feature-row" key={feature.feature_name}><span>{feature.feature_name}</span><b>{feature.importance.toFixed(3)}</b></div>)}</div></div><p className="disclaimer">These features contributed most strongly to the model prediction according to SHAP attribution; this does not prove physical causation.</p></> : <div className="panel empty-large"><ShieldCheck size={25} /><h3>No diagnosis available</h3><p>Analyze a CSV signal first. The diagnosis view will only show results from the real inference API.</p></div>}</>; }

function HistoryPage({ history }: { history: HistoryItem[] }) { return <div className="panel table-panel"><div className="panel-heading"><div><p className="eyebrow">PERSISTED RESULTS</p><h2>Prediction history</h2></div><History size={20} className="heading-icon" /></div><div className="table-wrap"><table><thead><tr><th>Condition</th><th>Machine</th><th>Health</th><th>Confidence</th><th>Timestamp</th></tr></thead><tbody>{history.length ? history.map(item => <tr key={item.id}><td><strong>{item.predicted_fault}</strong><small>{item.severity}</small></td><td>{item.machine_id}</td><td className={item.health_score < 60 ? 'danger-text' : 'good-text'}>{item.health_score.toFixed(0)}</td><td>{(item.confidence * 100).toFixed(1)}%</td><td>{item.timestamp}</td></tr>) : <tr><td colSpan={5} className="table-empty">No real predictions stored yet.</td></tr>}</tbody></table></div></div>; }

function SystemPage({ system, health }: { system: SystemStatus | null; health: HealthStatus | null }) { const components = system?.components || {}; return <><div className="lab-header"><div><p className="eyebrow">RUNTIME / OBSERVABILITY</p><h2>System status</h2><p className="muted large">Operational readiness of the current local prototype.</p></div><span className="status-chip online"><CheckCircle2 size={14} /> {system?.status || health?.status || 'UNKNOWN'}</span></div><div className="component-grid">{Object.entries(components).map(([name, state]) => <div className="panel component" key={name}><div className="component-icon"><CheckCircle2 size={18} /></div><div><strong>{name.split('_').join(' ')}</strong><small>{state}</small></div></div>)}</div><div className="panel detail-panel"><div><span className="eyebrow">ACTIVE MODEL</span><strong>{system?.active_model || 'N/A'}</strong><small>{system?.model_version || 'N/A'} · {system?.feature_count || 0} features</small></div><div><span className="eyebrow">ENVIRONMENT</span><strong>{health?.environment || 'N/A'}</strong><small>API v{health?.version || 'N/A'}</small></div><div><span className="eyebrow">DATA POLICY</span><strong>Explicit results only</strong><small>Demo labels remain visible</small></div></div></>; }
