// @ts-nocheck
import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import Plot from 'react-plotly.js';
import { Activity, BarChart3, CheckCircle2, Database, Gauge, History, RefreshCw, ShieldCheck, SlidersHorizontal, Upload } from 'lucide-react';

type Page = 'dashboard' | 'vmd' | 'diagnosis' | 'training' | 'history' | 'system';
type Status = { status: string; active_model?: string; model_version?: string; feature_count?: number; components?: Record<string, string> };
type Analysis = { sample_count: number; duration_sec: number; metadata: { sampling_rate: number }; time_stats: Record<string, number>; frequency_stats: Record<string, number>; time_series_preview: number[] };
type Vmd = { optimized_K: number; optimized_alpha: number; optimized_fitness: number; initial_fitness: number; reconstruction_error: number; imf_waveforms: number[][]; imf_stats: { imf_index: number; rms: number; energy: number; kurtosis: number; dominant_freq: number; spectral_entropy: number }[] };
type Prediction = { predicted_fault: string; confidence: number; severity: string; health_score: number; class_probabilities: Record<string, number>; top_features: { feature_name: string; importance: number }[]; recommended_action: string };
const pages = [{ id: 'dashboard', label: 'Dashboard', icon: Gauge }, { id: 'vmd', label: 'VMD Explorer', icon: BarChart3 }, { id: 'diagnosis', label: 'Fault Diagnosis', icon: ShieldCheck }, { id: 'training', label: 'Model Training', icon: Database }, { id: 'history', label: 'History', icon: History }, { id: 'system', label: 'System', icon: SlidersHorizontal }] as const;
const request = async (url: string, init?: RequestInit) => { const response = await fetch(url, init); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.detail || `HTTP ${response.status}`); return data; };
function Card({ children }: { children: ReactNode }) { return <section className="vg-card">{children}</section>; }
function PlotCard({ title, values }: { title: string; values: number[] }) { return <Card><div className="vg-section-title"><span>MEASURED SERVER OUTPUT</span><h2>{title}</h2></div><Plot data={[{ x: values.map((_, i) => i), y: values, type: 'scatter', mode: 'lines', line: { color: '#43d9c5', width: 1.5 } }]} layout={{ height: 280, margin: { l: 45, r: 15, t: 10, b: 40 }, paper_bgcolor: 'transparent', plot_bgcolor: 'transparent', font: { color: '#89aaa5' }, xaxis: { gridcolor: '#17383b' }, yaxis: { gridcolor: '#17383b' } }} config={{ responsive: true, displaylogo: false }} style={{ width: '100%' }} /></Card>; }
export default function AppFixed() {
	const [page, setPage] = useState<Page>('dashboard'); const [status, setStatus] = useState<Status | null>(null); const [analysis, setAnalysis] = useState<Analysis | null>(null); const [vmd, setVmd] = useState<Vmd | null>(null); const [prediction, setPrediction] = useState<Prediction | null>(null); const [history, setHistory] = useState<any[]>([]); const [file, setFile] = useState<File | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [model, setModel] = useState('Random Forest'); const [training, setTraining] = useState<any>(null);
 const refresh = async () => { try { const [s, h] = await Promise.all([request('/api/v1/system/status'), request('/api/v1/predict/history?limit=20')]); setStatus(s); setHistory(h); } catch (e) { setError(e instanceof Error ? e.message : 'Backend unavailable'); } };
 useEffect(() => { refresh(); }, []);
 const upload = async (nextFile: File) => { setFile(nextFile); setBusy(true); try { const form = new FormData(); form.append('file', nextFile); setAnalysis(await request('/api/v1/signal/upload', { method: 'POST', body: form })); setPage('vmd'); } catch (e) { setError(e instanceof Error ? e.message : 'Upload failed'); } finally { setBusy(false); } };
 const optimize = async () => { if (!file) return setError('Upload a CSV on Dashboard first.'); setBusy(true); try { const form = new FormData(); form.append('file', file); const signal = await request('/api/v1/signal/upload', { method: 'POST', body: form }); setAnalysis(signal); setVmd(await request('/api/v1/vmd/optimize', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ signal: signal.time_series_preview, sampling_rate: signal.metadata.sampling_rate, k_min: 3, k_max: 7 }) })); } catch (e) { setError(e instanceof Error ? e.message : 'VMD failed'); } finally { setBusy(false); } };
 const diagnose = async () => { if (!file) return setError('Upload a CSV on Dashboard first.'); setBusy(true); try { const form = new FormData(); form.append('file', file); setPrediction(await request('/api/v1/predict/file', { method: 'POST', body: form })); await refresh(); setPage('diagnosis'); } catch (e) { setError(e instanceof Error ? e.message : 'Diagnosis failed'); } finally { setBusy(false); } };
 const train = async () => { setBusy(true); try { setTraining(await request('/api/v1/system/train', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ model_name: model }) })); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Training failed'); } finally { setBusy(false); } };
 return <div className="vg-shell"><aside className="vg-sidebar"><div className="vg-brand"><div className="vg-logo"><Activity size={22} /></div><div><b>VIBRA<span>GUARD</span></b><small>Predictive maintenance</small></div></div><span className="vg-rail-label">CONTROL ROOM</span><nav>{pages.map(({ id, label, icon: Icon }) => <button className={page === id ? 'vg-nav active' : 'vg-nav'} onClick={() => setPage(id)} key={id}><Icon size={18} /><span>{label}</span></button>)}</nav><div className="vg-side-status"><i /> Sensor gateway ready</div></aside><main className="vg-main"><header className="vg-header"><div><span className="vg-eyebrow">MACHINE HEALTH / LIVE WORKSPACE</span><h1>{pages.find(item => item.id === page)?.label}</h1></div><div className="vg-header-actions"><span className="vg-status online"><i /> API ONLINE</span><button className="vg-icon-button" onClick={refresh}><RefreshCw size={16} /></button></div></header>{error && <div className="vg-error">{error}</div>}<div className="vg-content">{page === 'dashboard' && <Dashboard status={status} analysis={analysis} prediction={prediction} file={file} history={history} busy={busy} upload={upload} diagnose={diagnose} setPage={setPage} />}{page === 'vmd' && <VmdPage analysis={analysis} vmd={vmd} busy={busy} optimize={optimize} />}{page === 'diagnosis' && <Diagnosis prediction={prediction} />}{page === 'training' && <Training result={training} model={model} setModel={setModel} busy={busy} train={train} />}{page === 'history' && <HistoryPage history={history} />}{page === 'system' && <SystemPage status={status} />}</div></main></div>;
}
function Dashboard({ status, analysis, prediction, file, history, busy, upload, diagnose, setPage }: any) { return <><div className="vg-hero"><div><span className="vg-kicker"><i /> REAL API RESULTS / DEMO FIXTURES LABELED</span><h2>Machine health, without the guesswork.</h2><p>Upload a vibration window, decompose its modes, and inspect the model decision.</p></div><label className="vg-primary"><Upload size={16} /> {busy ? 'Processing...' : 'Upload CSV'}<input type="file" accept=".csv,.txt" onChange={(e: any) => e.target.files?.[0] && upload(e.target.files[0])} /></label></div><Card><div className="machine-name"><span className="vg-eyebrow">MACHINE</span><h3>Bearing Rig #01</h3><small>{file?.name || 'No signal selected'} · {status?.active_model || 'Model not loaded'}</small></div></Card><div className="vg-metrics"><Metric label="HEALTH SCORE" value={prediction ? `${prediction.health_score.toFixed(0)} / 100` : 'N/A'} detail="Engineering heuristic" /><Metric label="CONDITION" value={prediction?.predicted_fault || 'AWAITING SIGNAL'} detail={prediction?.severity || 'Upload a signal'} /><Metric label="CONFIDENCE" value={prediction ? `${(prediction.confidence * 100).toFixed(1)}%` : 'N/A'} detail="Model score" /><Metric label="MODEL" value={status?.model_version || 'N/A'} detail={`${status?.feature_count || 0} features`} /></div><div className="vg-two-col">{analysis ? <PlotCard title="Vibration signal" values={analysis.time_series_preview} /> : <Card><div className="vg-empty"><Activity size={25} /><h3>Signal canvas is clear</h3><p>Select a CSV to render measured telemetry.</p></div></Card>}<Card><div className="vg-section-title"><span>FAULT DIAGNOSIS</span><h2>{prediction?.predicted_fault || 'No diagnosis yet'}</h2></div><button className="vg-secondary" onClick={diagnose} disabled={!file || busy}><ShieldCheck size={15} /> Diagnose selected signal</button></Card></div><Card><div className="vg-section-title"><span>RECENT ALERTS</span><h2>Maintenance queue</h2><button className="vg-text-button" onClick={() => setPage('history')}>View history</button></div>{history.slice(0, 4).map(item => <div className="vg-event" key={item.id}><i /><div><b>{item.predicted_fault}</b><small>{item.machine_id} · {item.timestamp}</small></div><strong>{item.health_score.toFixed(0)}</strong></div>)}</Card></>; }
function Metric({ label, value, detail }: any) { return <div className="vg-metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }
function VmdPage({ analysis, vmd, busy, optimize }: any) { return <><div className="vg-page-intro"><div><span className="vg-eyebrow">SIGNAL → MODES → RECONSTRUCTION</span><h2>VMD Explorer</h2><p>Actual adaptive VMD output from the server.</p></div><button className="vg-primary" onClick={optimize} disabled={busy || !analysis}><BarChart3 size={15} /> {busy ? 'Optimizing...' : 'Run adaptive VMD'}</button></div>{analysis && <div className="vg-metrics"><Metric label="INPUT" value={`${analysis.sample_count}`} detail={`${analysis.metadata.sampling_rate} Hz`} /><Metric label="INITIAL FITNESS" value={vmd ? vmd.initial_fitness.toFixed(4) : 'N/A'} detail="Measured baseline" /><Metric label="OPTIMIZED FITNESS" value={vmd ? vmd.optimized_fitness.toFixed(4) : 'N/A'} detail="Lower is better" /><Metric label="RECONSTRUCTION" value={vmd ? `${(vmd.reconstruction_error * 100).toFixed(3)}%` : 'N/A'} detail="Relative L2 error" /></div>}{vmd ? <><Card><div className="vg-section-title"><span>IMF WAVEFORMS</span><h2>{vmd.imf_waveforms.length} intrinsic mode functions</h2></div>{vmd.imf_waveforms.map((wave: number[], i: number) => <PlotCard key={i} title={`IMF ${i + 1}`} values={wave} />)}</Card><Card><div className="vg-section-title"><span>MODE METRICS</span><h2>Per-IMF indicators</h2></div><div className="vg-table-wrap"><table><thead><tr><th>IMF</th><th>RMS</th><th>Energy</th><th>Kurtosis</th><th>Dominant Hz</th><th>Entropy</th></tr></thead><tbody>{vmd.imf_stats.map(stat => <tr key={stat.imf_index}><td>{stat.imf_index}</td><td>{stat.rms.toFixed(5)}</td><td>{stat.energy.toFixed(4)}</td><td>{stat.kurtosis.toFixed(3)}</td><td>{stat.dominant_freq.toFixed(2)}</td><td>{stat.spectral_entropy.toFixed(3)}</td></tr>)}</tbody></table></div></Card></> : <Card><div className="vg-empty"><BarChart3 size={25} /><h3>Run adaptive VMD to inspect IMFs</h3></div></Card>}</>; }
function Diagnosis({ prediction }: { prediction: Prediction | null }) { return prediction ? <><div className="vg-diagnosis-head"><div><span className="vg-eyebrow">REAL MODEL PREDICTION</span><h2>{prediction.predicted_fault}</h2><p>{prediction.recommended_action}</p></div><div className="vg-score"><strong>{prediction.health_score.toFixed(0)}</strong><small>HEALTH / 100</small></div></div><div className="vg-two-col"><Card><div className="vg-section-title"><span>CLASS PROBABILITY</span><h2>Model scores</h2></div>{Object.entries(prediction.class_probabilities).map(([key, value]) => <div className="vg-prob" key={key}><span>{key}</span><b>{(Number(value) * 100).toFixed(1)}%</b><i><em style={{ width: `${Number(value) * 100}%` }} /></i></div>)}</Card><Card><div className="vg-section-title"><span>SHAP LOCAL ATTRIBUTION</span><h2>Top features</h2></div>{prediction.top_features.map(feature => <div className="vg-feature" key={feature.feature_name}><span>{feature.feature_name}</span><b>{feature.importance.toFixed(4)}</b></div>)}</Card></div></> : <Card><div className="vg-empty"><ShieldCheck size={25} /><h3>No diagnosis available</h3></div></Card>; }
function Training({ result, model, setModel, busy, train }: any) { return <><div className="vg-page-intro"><div><span className="vg-eyebrow">MODEL LIFECYCLE / REAL METRICS</span><h2>Model Training</h2></div><div className="vg-actions"><select value={model} onChange={e => setModel(e.target.value)}><option>Random Forest</option><option>Gradient Boosting</option><option>SVM</option><option>Logistic Regression</option></select><button className="vg-primary" onClick={train} disabled={busy}><Database size={15} /> {busy ? 'Training...' : 'Train model'}</button></div></div>{result ? <Card><div className="vg-metrics"><Metric label="VERSION" value={result.metadata.version} detail={result.metadata.model_name} /><Metric label="ACCURACY" value={`${(result.metadata.accuracy * 100).toFixed(1)}%`} detail="Grouped holdout" /><Metric label="MACRO F1" value={`${(result.metadata.macro_f1 * 100).toFixed(1)}%`} detail="Real predictions" /><Metric label="ROC-AUC" value={result.metadata.roc_auc == null ? 'N/A' : result.metadata.roc_auc.toFixed(3)} detail="Binary score" /></div></Card> : <Card><div className="vg-empty"><Database size={25} /><h3>No training run yet</h3></div></Card>}</>; }
function HistoryPage({ history }: any) { return <Card><div className="vg-section-title"><span>SQLITE PERSISTENCE</span><h2>Prediction history</h2></div><div className="vg-table-wrap"><table><thead><tr><th>Condition</th><th>Machine</th><th>Health</th><th>Confidence</th><th>Time</th></tr></thead><tbody>{history.map(item => <tr key={item.id}><td>{item.predicted_fault}<small>{item.severity}</small></td><td>{item.machine_id}</td><td>{item.health_score.toFixed(0)}</td><td>{(item.confidence * 100).toFixed(1)}%</td><td>{item.timestamp}</td></tr>)}</tbody></table></div></Card>; }
function SystemPage({ status }: { status: Status | null }) { return <><div className="vg-page-intro"><div><span className="vg-eyebrow">RUNTIME / OBSERVABILITY</span><h2>System status</h2></div><span className="vg-status online"><CheckCircle2 size={14} /> {status?.status || 'UNKNOWN'}</span></div><div className="vg-system-grid">{Object.entries(status?.components || {}).map(([name, value]) => <Card key={name}><CheckCircle2 size={18} /><b>{name.split('_').join(' ')}</b><small>{value}</small></Card>)}</div></>; }
